export const Msblok = [
  {
    IDBlok: Math.floor(Math.random() * 9999),
    KodeBlok: "E001A031",
    UnitUsaha: "TS1",
    Afdeling: "E001AFDI01",
    Owner: "Inti",
    StatusTanaman: "TM",
    Topografi: "Datar",
    LuasTanah: "30,65",
    LuasTanahTertanam: "30,65",
    JumlahPohon: "1.000",
  },
  {
    IDBlok: Math.floor(Math.random() * 9999),
    KodeBlok: "E001G003",
    UnitUsaha: "TS1",
    Afdeling: "E001AFDI02",
    Owner: "Inti",
    StatusTanaman: "TM",
    Topografi: "Datar",
    LuasTanah: "28,05",
    LuasTanahTertanam: "26,65",
    JumlahPohon: "1.000",
  },
];
