export const MsKendaraanDanMesin = [
  {
    IDMsKendaraanDanMesin: Math.floor(Math.random() * 9999),
    KodeOperasional: "DT01-AGI",
    InternalOrder: "E001KRD901",
    NomorPolisi: "B 9471 BDB",
    NomorRangka: "4D34TG21725",
    NomorMesin: "MHMFE74P5BK044568",
    Merk: "Mitsubishi",
    Model: "HDX",
    JenisKendaraanDanMesin: "Dump Truck (Kecil)",
    Tipe: "Kendaraan",
    NamaUnitUsaha: "TSE",
    TahunPerolehan: 2023,
  },
  {
    IDMsKendaraanDanMesin: Math.floor(Math.random() * 9999),
    KodeOperasional: "DT02-AGI",
    InternalOrder: "E001KRD902",
    NomorPolisi: "B 9400 BDB",
    NomorRangka: "4D34TG21725",
    NomorMesin: "MHMFE74P5BK044568",
    Merk: "Mitsubishi",
    Model: "HDX",
    JenisKendaraanDanMesin: "Dump Truck (Kecil)",
    Tipe: "Kendaraan",
    NamaUnitUsaha: "TSE",
    TahunPerolehan: 2023,
  },
  {
    IDMsKendaraanDanMesin: Math.floor(Math.random() * 9999),
    KodeOperasional: "EXC02-AGI",
    InternalOrder: "E001ABC902",
    NomorPolisi: "",
    NomorRangka: "4D34TG21725",
    NomorMesin: "MHMFE74P5BK044568",
    Merk: "CAT",
    Model: "CAT",
    JenisKendaraanDanMesin: "Excavator",
    Tipe: "Alat Berat",
    NamaUnitUsaha: "TSE",
    TahunPerolehan: 2023,
  },
];
