export const MsKegiatanDetail = [
  {
    IDMsKegiatan: Math.floor(Math.random() * 9999),
    KegiatanHeader: "PANEN",
    Kegiatan: "PEMANEN",
    AktifitasLapangan: "PANEN (POTONG BUAH)",
    Output01: "JJG",
    Output02: "HA",
    Output03: "KG BL",
    IsMaterial: false,
    MainGL: "70110, 82110, 83110",
  },
  {
    IDMsKegiatan: Math.floor(Math.random() * 9999),
    KegiatanHeader: "PANEN",
    Kegiatan: "PEMANEN",
    AktifitasLapangan: "GERDANG PANEN",
    Output01: "-",
    Output02: "-",
    Output03: "-",
    IsMaterial: false,
    MainGL: "70110, 82110, 83110",
  },
  {
    IDMsKegiatan: Math.floor(Math.random() * 9999),
    KegiatanHeader: "PANEN",
    Kegiatan: "PEMANEN",
    AktifitasLapangan: "KUTIP BRONDOLAN DI PIRINGAN",
    Output01: "-",
    Output02: "-",
    Output03: "-",
    IsMaterial: false,
    MainGL: "70110, 82110, 83110",
  },
  {
    IDMsKegiatan: Math.floor(Math.random() * 9999),
    KegiatanHeader: "PANEN",
    Kegiatan: "PEMANEN",
    AktifitasLapangan: "BORONGAN PANEN",
    Output01: "JJG",
    Output02: "HA",
    Output03: "KG BL",
    IsMaterial: false,
    MainGL: "70110, 82110, 83110",
  },{
    IDMsKegiatan: Math.floor(Math.random() * 9999),
    KegiatanHeader: "PANEN",
    Kegiatan: "PENGANGKUTAN HASIL PANEN",
    AktifitasLapangan: "MUAT TBS DARI TPH KE PKS",
    Output01: "TON",
    Output02: "JJG",
    Output03: "BLOK",
    IsMaterial: false,
    MainGL: "70110, 82110, 83110",
  },
];
