export const MsMenu = [
  {
    IDMsMenu: Math.floor(Math.random() * 9999),
    Menu: "Dashboard",
    Path: "",
    IsParrent: false,
    Level: 0,
    IsCreate: false,
    IsRead: false,
    IsUpdate: false,
    IsDelete: false,
    IsPark: false,
    IsPost: false,
    IsUndo: false,
    IsExport: false,
  },
  {
    IDMsMenu: Math.floor(Math.random() * 9999),
    Menu: "Master Data",
    Path: "Master Data",
    IsParrent: true,
    Level: 0,
    IsCreate: false,
    IsRead: false,
    IsUpdate: false,
    IsDelete: false,
    IsPark: false,
    IsPost: false,
    IsUndo: false,
    IsExport: false,
  },
  {
    IDMsMenu: Math.floor(Math.random() * 9999),
    Menu: "PT",
    Path: "Master Data / PT",
    IsParrent: false,
    Level: 1,
    IsCreate: false,
    IsRead: false,
    IsUpdate: false,
    IsDelete: false,
    IsPark: false,
    IsPost: false,
    IsUndo: false,
    IsExport: false,
  },
  {
    IDMsMenu: Math.floor(Math.random() * 9999),
    Menu: "Unit Usaha",
    Path: "Master Data / Unit Usaha",
    IsParrent: false,
    Level: 1,
    IsCreate: false,
    IsRead: false,
    IsUpdate: false,
    IsDelete: false,
    IsPark: false,
    IsPost: false,
    IsUndo: false,
    IsExport: false,
  },
  {
    IDMsMenu: Math.floor(Math.random() * 9999),
    Menu: "Afdeling",
    Path: "Master Data / Afdeling",
    IsParrent: false,
    Level: 1,
    IsCreate: false,
    IsRead: false,
    IsUpdate: false,
    IsDelete: false,
    IsPark: false,
    IsPost: false,
    IsUndo: false,
    IsExport: false,
  },
];
