export const MsRolePermission = [
  {
    IDMsRolePermission: Math.floor(Math.random() * 999),
    NamaRole: "Role Administrator",
    KodeRole: "ADMIN",
    Menu: "PT",
    IsCreate: true,
    IsRead: true,
    IsUpdate: true,
    IsDelete: true,
    IsPark: false,
    IsPost: false,
    IsUndo: false,
    IsExport: true,
  },
  {
    IDMsRolePermission: Math.floor(Math.random() * 999),
    NamaRole: "Role Administrator",
    KodeRole: "ADMIN",
    Menu: "Unit Usaha",
    IsCreate: true,
    IsRead: true,
    IsUpdate: true,
    IsDelete: true,
    IsPark: false,
    IsPost: false,
    IsUndo: false,
    IsExport: true,
  },
  {
    IDMsRolePermission: Math.floor(Math.random() * 999),
    NamaRole: "Role Kasie TSE",
    KodeRole: "KSITSE",
    Menu: "Unit Usaha",
    IsCreate: false,
    IsRead: true,
    IsUpdate: false,
    IsDelete: false,
    IsPark: false,
    IsPost: false,
    IsUndo: false,
    IsExport: true,
  },
];
