export const MsUnitUsaha = [
  {
    IDMsUnitUsaha: Math.floor(Math.random() * 9999),
    KodeUnitUsaha: "E001",
    AliasPT: "TBP",
    NamaUnitUsaha: "Talisayan Estate",
    Alias: "TSE",
    Alamat: "Jl. Test Desa Test",
    Manager: "Manager TSE",
    KasiePembukuan: "Kasie Pembukuan TSE",
    KasieTanaman: "Kasie Tanaman TSE",
  },
  {
    IDMsUnitUsaha: Math.floor(Math.random() * 9999),
    KodeUnitUsaha: "E004",
    AliasPT: "TBP",
    NamaUnitUsaha: "Biatan Estate",
    Alias: "BTE",
    Alamat: "Jl. Test Desa Test", 
    Manager: "Manager BTE",
    KasiePembukuan: "Kasie Pembukuan BTE",
    KasieTanaman: "",
  },
  {
    IDMsUnitUsaha: Math.floor(Math.random() * 9999),
    KodeUnitUsaha: "M001",
    AliasPT: "TBP",
    NamaUnitUsaha: "Talisayan Mill",
    Alias: "TSM",
    Alamat: "Jl. Test Desa Test", 
    Manager: "Manager TSM",
    KasiePembukuan: "Kasie Pembukuan TSM",
    KasieTanaman: "",
  },
  
  {
    IDMsUnitUsaha: Math.floor(Math.random() * 9999),
    KodeUnitUsaha: "E005",
    AliasPT: "INK",
    NamaUnitUsaha: "Ampen Medang Estate",
    Alias: "AME",
    Alamat: "Jl. Test Desa Test", 
    Manager: "Manager AME",
    KasiePembukuan: "Kasie Pembukuan AME",
    KasieTanaman: "Kasie Tanaman AME",
  },
];
