export const MsUserRoleScope = [
  {
    IDMsUserScope: Math.floor(Math.random() * 999),
    NamaUserScope: "Scope All",
    KodePT: "*",
    NamaPT: "*",
    KodeUnitUsaha: "*",
    NamaUnitUsaha: "*",
    KodeAfdeling: "*",
    Username: "Administrator",
    NamaRole: "Role Administrator",
    KodeRole: "ADMIN",
  },
  {
    IDMsUserScope: Math.floor(Math.random() * 999),
    NamaUserScope: "Scope All",
    KodePT: "*",
    NamaPT: "*",
    KodeUnitUsaha: "*",
    NamaUnitUsaha: "*",
    KodeAfdeling: "*",
    Username: "Zakie",
    NamaRole: "Role Akunting",
    KodeRole: "ACCT",
  },
  {
    IDMsUserScope: Math.floor(Math.random() * 999),
    NamaUserScope: "Scope TSE",
    KodePT: "1100",
    NamaPT: "TBP",
    KodeUnitUsaha: "E001",
    NamaUnitUsaha: "TSE",
    KodeAfdeling: "*",
    Username: "Ahdiana",
    NamaRole: "Role GAO",
    KodeRole: "GAO",
  },
  {
    IDMsUserScope: Math.floor(Math.random() * 999),
    NamaUserScope: "Scope TSE",
    KodePT: "1100",
    NamaPT: "TBP",
    KodeUnitUsaha: "E001",
    NamaUnitUsaha: "TSE",
    KodeAfdeling: "*",
    Username: "Tresa",
    NamaRole: "Role Kasie",
    KodeRole: "KASIE",
  },

  {
    IDMsUserScope: Math.floor(Math.random() * 999),
    NamaUserScope: "Scope BTE",
    KodePT: "1100",
    NamaPT: "TBP",
    KodeUnitUsaha: "E004",
    NamaUnitUsaha: "BTE",
    KodeAfdeling: "*",
    Username: "Ahdiana",
    NamaRole: "Role GAO",
    KodeRole: "GAO",
  },
  {
    IDMsUserScope: Math.floor(Math.random() * 999),
    NamaUserScope: "Scope BTE",
    KodePT: "1100",
    NamaPT: "TBP",
    KodeUnitUsaha: "E004",
    NamaUnitUsaha: "BTE",
    KodeAfdeling: "*",
    Username: "Yamin",
    NamaRole: "Role Kasie",
    KodeRole: "KASIE",
  },
  {
    IDMsUserScope: Math.floor(Math.random() * 999),
    NamaUserScope: "Scope AME",
    KodePT: "1200",
    NamaPT: "INK",
    KodeUnitUsaha: "E005",
    NamaUnitUsaha: "AME",
    KodeAfdeling: "*",
    Username: "Ahdiana",
    NamaRole: "Role GAO",
    KodeRole: "GAO",
  },
  {
    IDMsUserScope: Math.floor(Math.random() * 999),
    NamaUserScope: "Scope TSM",
    KodePT: "1100",
    NamaPT: "TBP",
    KodeUnitUsaha: "M001",
    NamaUnitUsaha: "TSM",
    KodeAfdeling: "*",
    Username: "Kasie TSM",
    NamaRole: "Role Kasie",
    KodeRole: "KASIE",
  },
  {
    IDMsUserScope: Math.floor(Math.random() * 999),
    NamaUserScope: "Scope AME Afd 01",
    KodePT: "1200",
    NamaPT: "INK",
    KodeUnitUsaha: "E005",
    NamaUnitUsaha: "AME",
    KodeAfdeling: "E005AFDI01",
    Username: "E005OPR001",
    NamaRole: "Role Operator Komputer",
    KodeRole: "OPRKOM",
  },
];
