export const MsUserScope = [
  {
    IDMsUserScope: Math.floor(Math.random() * 999),
    NamaUserScope: "Scope All",
    KodePT: "*",
    NamaPT: "*",
    KodeUnitUsaha: "*",
    NamaUnitUsaha: "*",
    KodeAfdeling: "*",
    Username: "Administrator",
  },
  {
    IDMsUserScope: Math.floor(Math.random() * 999),
    NamaUserScope: "Scope All",
    KodePT: "*",
    NamaPT: "*",
    KodeUnitUsaha: "*",
    NamaUnitUsaha: "*",
    KodeAfdeling: "*",
    Username: "Zakie",
  },
  {
    IDMsUserScope: Math.floor(Math.random() * 999),
    NamaUserScope: "Scope TSE",
    KodePT: "1100",
    NamaPT: "TBP",
    KodeUnitUsaha: "E001",
    NamaUnitUsaha: "TSE",
    KodeAfdeling: "*",
    Username: "Ahdiana",
  },
  {
    IDMsUserScope: Math.floor(Math.random() * 999),
    NamaUserScope: "Scope TSE",
    KodePT: "1100",
    NamaPT: "TBP",
    KodeUnitUsaha: "E001",
    NamaUnitUsaha: "TSE",
    KodeAfdeling: "*",
    Username: "Tresa",
  },

  {
    IDMsUserScope: Math.floor(Math.random() * 999),
    NamaUserScope: "Scope BTE",
    KodePT: "1100",
    NamaPT: "TBP",
    KodeUnitUsaha: "E004",
    NamaUnitUsaha: "BTE",
    KodeAfdeling: "*",
    Username: "Ahdiana",
  },
  {
    IDMsUserScope: Math.floor(Math.random() * 999),
    NamaUserScope: "Scope BTE",
    KodePT: "1100",
    NamaPT: "TBP",
    KodeUnitUsaha: "E004",
    NamaUnitUsaha: "BTE",
    KodeAfdeling: "*",
    Username: "Yamin",
  },
  {
    IDMsUserScope: Math.floor(Math.random() * 999),
    NamaUserScope: "Scope AME",
    KodePT: "1200",
    NamaPT: "INK",
    KodeUnitUsaha: "E005",
    NamaUnitUsaha: "AME",
    KodeAfdeling: "*",
    Username: "Ahdiana",
  },
  {
    IDMsUserScope: Math.floor(Math.random() * 999),
    NamaUserScope: "Scope TSM",
    KodePT: "1100",
    NamaPT: "TBP",
    KodeUnitUsaha: "M001",
    NamaUnitUsaha: "TSM",
    KodeAfdeling: "*",
    Username: "Kasie TSM",
  },
  {
    IDMsUserScope: Math.floor(Math.random() * 999),
    NamaUserScope: "Scope Testing",
    KodePT: "*",
    NamaPT: "*",
    KodeUnitUsaha: "*",
    NamaUnitUsaha: "*",
    KodeAfdeling: "*",
  },{
    IDMsUserScope: Math.floor(Math.random() * 999),
    NamaUserScope: "Scope AME Afd 01",
    KodePT: "1200",
    NamaPT: "INK",
    KodeUnitUsaha: "E005",
    NamaUnitUsaha: "AME",
    KodeAfdeling: "E005AFDI01",
    Username: "E005OPR001",
  },
];
